# Generated by Django 4.2.2 on 2023-06-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок заметки')),
                ('content', models.TextField(verbose_name='Содержание заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата, время создания')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Название тега')),
                ('notes', models.ManyToManyField(to='main.note')),
            ],
        ),
    ]
