# Generated by Django 4.2.2 on 2023-06-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
