# Generated by Django 4.2.2 on 2023-07-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='notes',
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(to='main.tag'),
        ),
    ]
